name: Bump casks on schedule or request

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: read

jobs:
  autobump:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: false
          cask: true
          test-bot: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'emilymclean' }}

      - name: Bump casks
        uses: Homebrew/actions/bump-packages@master
        continue-on-error: true
        with:
          token: ${{ secrets.HOMEBREW_CASK_REPO_WORKFLOW_TOKEN }}
          casks: "fladder"
        env:
          HOMEBREW_TEST_BOT_AUTOBUMP: 1
